// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kcmqpbqkwgfqmfbjgrlr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtjbXFwYnFrd2dmcW1mYmpncmxyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MDc1ODMsImV4cCI6MjA2NTQ4MzU4M30.2lgEQZjyf9apBFMvrs-xWuZAdlZ-1JA6oTqJyRiAeq4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);